name: Arkanoid CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'examples/arkanoid/**'
      - '!examples/arkanoid/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/arkanoid.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'examples/arkanoid/**'
      - '!examples/arkanoid/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/arkanoid.yml'

concurrency:
  group: arkanoid-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/example_reusable.yml
    with:
      job_name: Arkanoid CI
      working_directory: examples/arkanoid
