name: Asteroids Example CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'examples/asteroids/**'
      - '!examples/asteroids/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/asteroids.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'examples/asteroids/**'
      - '!examples/asteroids/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/asteroids.yml'

concurrency:
  group: asteroids-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/example_reusable.yml
    with:
      job_name: Asteroids Example CI
      working_directory: examples/asteroids
