name: Connect Four CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'examples/connect_four/**'
      - '!examples/connect_four/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/connect_four.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'examples/connect_four/**'
      - '!examples/connect_four/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/connect_four.yml'

concurrency:
  group: connect-four-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/example_reusable.yml
    with:
      job_name: Connect Four CI
      working_directory: examples/connect_four
