name: Pokemon Mini CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'examples/pokemon_mini/**'
      - '!examples/pokemon_mini/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/pokemon_mini.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'examples/pokemon_mini/**'
      - '!examples/pokemon_mini/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/pokemon_mini.yml'

concurrency:
  group: pokemon-mini-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/example_reusable.yml
    with:
      job_name: Pokemon Mini CI
      working_directory: examples/pokemon_mini
