name: Proof of Hunt CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'examples/proof_of_hunt/**'
      - '!examples/proof_of_hunt/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/proof_of_hunt.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'examples/proof_of_hunt/**'
      - '!examples/proof_of_hunt/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/proof_of_hunt.yml'

concurrency:
  group: proof-of-hunt-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/example_reusable.yml
    with:
      job_name: Proof of Hunt CI
      working_directory: examples/proof_of_hunt
