name: Tic Tac Toe Example CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'examples/tic_tac_toe/**'
      - '!examples/tic_tac_toe/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/tic_tac_toe.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'examples/tic_tac_toe/**'
      - '!examples/tic_tac_toe/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/tic_tac_toe.yml'

concurrency:
  group: tic-tac-toe-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/example_reusable.yml
    with:
      job_name: Tic Tac Toe Example CI
      working_directory: examples/tic_tac_toe
