name: Treasure Hunt CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'examples/treasure_hunt/**'
      - '!examples/treasure_hunt/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/treasure_hunt.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'examples/treasure_hunt/**'
      - '!examples/treasure_hunt/**/*.md'
      - '.github/workflows/example_reusable.yml'
      - '.github/workflows/treasure_hunt.yml'

concurrency:
  group: treasure-hunt-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/example_reusable.yml
    with:
      job_name: Treasure Hunt CI
      working_directory: examples/treasure_hunt
